### ISSUE TITLE
Support for new Shopify custom apps

### ISSUE THREAD

**Issue by codeadict** [pixelunion-apps/elixir-shopifyapi#432]
Shopify recently upgraded to a new Custom apps experience that seems like is not being supported by this library, read announcement and documentation at https://changelog.shopify.com/posts/introducing-a-new-custom-app-experience.

**Comment by hez** [comment]
Good eye, yeah Private Apps are no longer supported.  This library was never really intended to be a Private App but more a Dev, Custom, or Published App.

Cheers
